# Generated by Django 4.2.1 on 2023-05-31 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app1', '0003_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='app1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
