# Generated by Django 4.2.1 on 2023-05-31 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_register_delete_app1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='email',
        ),
        migrations.RemoveField(
            model_name='register',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='register',
            name='password_1',
        ),
        migrations.RemoveField(
            model_name='register',
            name='phone',
        ),
    ]
