# Generated by Django 4.2.1 on 2023-05-31 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_remove_register_email_remove_register_lastname_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='register',
        ),
    ]
